import type {APIContext} from'astro';
const sources=[
{id:'jp-securities-weekly',domain:'CROSS-BORDER',label:'Japan International Transactions in Securities',status:'CONNECTED',cadence:'weekly',publisher:'Ministry of Finance Japan',url:'https://www.mof.go.jp/english/policy/international_policy/reference/itn_transactions_in_securities/index.htm',coverage:'Residents foreign securities + nonresidents Japanese securities',note:'Official weekly/monthly designated-major-investor series. From Jan 2014, positive outward net means net purchases.'},
{id:'us-tic-transactions',domain:'CROSS-BORDER',label:'U.S. TIC Long-term Securities Transactions',status:'CONNECTED',cadence:'monthly',publisher:'U.S. Department of the Treasury',url:'https://home.treasury.gov/data/treasury-international-capital-tic-system-home-page/tic-forms-instructions/securities-a-us-transactions-with-foreign-residents-in-long-term-securities',coverage:'Cross-border purchases/sales of long-term U.S. and foreign securities',note:'Expanded SLT transaction series has a break beginning Feb 2023; dashboard must not splice old/new definitions without annotation.'},
{id:'us-tic-holdings',domain:'BONDS',label:'U.S. TIC Securities Holdings',status:'CONNECTED',cadence:'monthly',publisher:'U.S. Department of the Treasury',url:'https://home.treasury.gov/data/treasury-international-capital-tic-system-home-page/tic-forms-instructions/securities-b-portfolio-holdings-of-us-and-foreign-securities',coverage:'Foreign holdings of U.S. securities incl. major foreign Treasury holders',note:'Custodial attribution can misstate ultimate country ownership; use as evidence, not perfect beneficial-owner truth.'},
{id:'cftc-positioning',domain:'FX / POSITIONING',label:'CFTC Commitments of Traders',status:'NEXT',cadence:'weekly',publisher:'CFTC',url:'https://www.cftc.gov/MarketReports/CommitmentsofTraders/index.htm',coverage:'Futures positioning',note:'Next connector candidate; positioning is not the same as cash cross-border flow.'},
{id:'central-bank',domain:'CENTRAL BANKS',label:'Fed / BOJ / ECB primary series',status:'NEXT',cadence:'weekly/monthly',publisher:'Primary central banks',url:null,coverage:'Policy rates, balance sheets, liquidity',note:'Wire primary series separately; do not infer policy liquidity solely from asset prices.'}
];
export const GET=async(_c:APIContext)=>new Response(JSON.stringify({ok:true,asOf:new Date().toISOString(),sources}),{headers:{'Content-Type':'application/json','Cache-Control':'private, max-age=3600'}});
