import type { AtlasNode } from './types';

// 8 initial nodes (from 7-DIM CARDS concept)
export const INITIAL_NODES: AtlasNode[] = [
  {
    id: 'ace-3month-coaching',
    title: 'ACE 3ヶ月集中コーチング',
    excerpt: '脳科学×アスリート経験。12週で脳の使い方を構造から書き換える。¥298,000。',
    tags: ['ACE', 'コーチング', '高単価', 'FUJISAN-PEAK'],
    axes: { 社会性: 0.7, 情熱度: 0.9, 収益性: 0.85, 難易度: 0.7, 持続性: 0.85, 公開性: 0.6, 唯一性: 0.98 },
    children: [],
    position: { x: 100, y: 80 },
  },
  {
    id: 'athlete-quest',
    title: 'Athlete Quest',
    excerpt: '3人ギルド構造のコミュニティ。トリエドュケーション。月額制。',
    tags: ['ACE', 'コミュニティ', 'FUJISAN-BASE'],
    axes: { 社会性: 0.95, 情熱度: 0.75, 収益性: 0.5, 難易度: 0.4, 持続性: 0.7, 公開性: 0.8, 唯一性: 0.85 },
    children: [],
    position: { x: 500, y: 80 },
  },
  {
    id: 'layer-zero-work',
    title: '第0層ワーク',
    excerpt: '身体感覚から入る。片足立ちで扁桃体を観察する。脳の入り口。',
    tags: ['基礎', '身体', '第0層'],
    axes: { 社会性: 0.2, 情熱度: 0.85, 収益性: 0.3, 難易度: 0.3, 持続性: 0.9, 公開性: 0.9, 唯一性: 0.95 },
    children: [],
    position: { x: -200, y: 280 },
  },
  {
    id: '13to-self',
    title: '13歳の自分へ',
    excerpt: 'ACEのコアメッセージ。13歳の自分に伝えたかったこと。発信の原点。',
    tags: ['思想', '発信', '原点'],
    axes: { 社会性: 0.6, 情熱度: 0.95, 収益性: 0.2, 難易度: 0.5, 持続性: 1.0, 公開性: 0.7, 唯一性: 0.9 },
    children: [],
    position: { x: 100, y: 380 },
  },
  {
    id: 'ace-no-mori',
    title: 'ACE no MORI (構想)',
    excerpt: '国立市に拠点を作る。アスリートが集まれる森。構想段階。',
    tags: ['拠点', '構想', 'Phase3'],
    axes: { 社会性: 0.9, 情熱度: 0.9, 収益性: 0.6, 難易度: 0.95, 持続性: 0.95, 公開性: 0.4, 唯一性: 1.0 },
    children: [],
    position: { x: 700, y: 380 },
  },
  {
    id: 'flow-v2-frame',
    title: 'FLOW v2 カリキュラム',
    excerpt: '12週のACEコーチングの骨格。4フェーズ(F-L-O-W)で構成。',
    tags: ['カリキュラム', 'FLOW', '12週'],
    axes: { 社会性: 0.4, 情熱度: 0.8, 収益性: 0.7, 難易度: 0.6, 持続性: 0.85, 公開性: 0.3, 唯一性: 0.88 },
    children: [],
    position: { x: -200, y: 480 },
  },
  {
    id: 'comparison-three-principles',
    title: '比較三原則',
    excerpt: '比較は止められない。だが燃やされる必要はない。ACEの核心コンセプト。',
    tags: ['コンセプト', '比較', '発信素材'],
    axes: { 社会性: 0.5, 情熱度: 0.85, 収益性: 0.4, 難易度: 0.35, 持続性: 0.95, 公開性: 0.95, 唯一性: 0.92 },
    children: [],
    position: { x: 300, y: 480 },
  },
  {
    id: 'cognitive-traits-report',
    title: '認知特性レポート',
    excerpt: '15問・3型診断。ドーパミン/セロトニン/オキシトシン型。Coconalaで販売中。',
    tags: ['診断', '認知特性', 'LP'],
    axes: { 社会性: 0.6, 情熱度: 0.7, 収益性: 0.65, 難易度: 0.4, 持続性: 0.7, 公開性: 0.85, 唯一性: 0.8 },
    children: [],
    position: { x: 700, y: 480 },
  },
];
