import{useMemo}from'react';
type Evidence={domain:string;metric:string;state:'CONNECTED'|'PROXY'|'UNKNOWN';source:string;meaning:string;next:string};
export default function MeasuredFlowLayer(){const rows=useMemo<Evidence[]>(()=>[
{domain:'EQUITY FLOWS',metric:'ETF / fund net flows',state:'UNKNOWN',source:'Dedicated flow provider not connected',meaning:'価格上昇と実際の純流入を分離する',next:'licensed/public fund-flow sourceを接続'},
{domain:'BONDS',metric:'Treasury / JGB flows',state:'PROXY',source:'Market OS: US 10Y price/yield sensor',meaning:'現在は金利変化を圧力proxyとして観察',next:'Treasury TIC / Japan portfolio-flow seriesへ拡張'},
{domain:'FX',metric:'Cross-border currency pressure',state:'PROXY',source:'USDJPY + DXY sensors',meaning:'通貨価格の方向を観察。実需フローとは区別',next:'CFTC positioning / balance-of-payments evidenceを追加'},
{domain:'CENTRAL BANKS',metric:'Policy / liquidity',state:'UNKNOWN',source:'Primary-source ingestion not wired to dashboard',meaning:'政策金利・バランスシート・声明を価格と接続する',next:'Fed / BOJ / ECB primary seriesを接続'},
{domain:'CROSS-BORDER',metric:'International capital movement',state:'UNKNOWN',source:'Official flow series not connected',meaning:'国境を越える証券投資・資本移動を実測する',next:'US TIC / Japan MOF / official BoP seriesを接続'},
{domain:'REAL ASSETS',metric:'Gold / Oil / Copper pressure',state:'PROXY',source:'Market OS price sensors',meaning:'実物資産への相対圧力を価格から観察',next:'inventory / positioning / ETF holdingsで裏取り'}
],[]);return <section className="mfl"><style>{`.mfl{margin:18px 0;border:1px solid #2E2822;background:#15120f;padding:16px}.head{display:flex;justify-content:space-between;gap:12px;align-items:flex-end}.ey{color:#7A6F5F;font-size:.65rem;letter-spacing:.11em}.title{margin-top:3px;color:#C9A96E;font:300 1.25rem 'Cormorant Garamond',serif}.legend{color:#7A6F5F;font-size:.66rem}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:13px}.card{border:1px solid #2E2822;background:#1A1612;padding:12px}.top{display:flex;justify-content:space-between;gap:8px}.domain{color:#8B7355;font-size:.64rem;letter-spacing:.08em}.state{font-size:.6rem;padding:2px 5px;border:1px solid #3A332B;color:#B9A17B}.metric{margin-top:7px;color:#D4C5A9;font-size:.82rem;font-weight:700}.source,.meaning,.next{margin-top:6px;color:#7A6F5F;font-size:.68rem;line-height:1.45}.next b{color:#8B7355}.foot{margin-top:10px;padding-top:9px;border-top:1px solid #2E2822;color:#7A6F5F;font-size:.67rem;line-height:1.5}@media(max-width:900px){.grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:560px){.grid{grid-template-columns:1fr}.head{display:block}.legend{margin-top:5px}}`}</style><div className="head"><div><div className="ey">MEASURED FLOW · EVIDENCE LADDER</div><div className="title">Price pressure → measured money</div></div><div className="legend">CONNECTED = 実測 / PROXY = 代替観測 / UNKNOWN = 未接続</div></div><div className="grid">{rows.map(r=><article className="card" key={r.domain}><div className="top"><span className="domain">{r.domain}</span><span className="state">{r.state}</span></div><div className="metric">{r.metric}</div><div className="source">SOURCE · {r.source}</div><div className="meaning">{r.meaning}</div><div className="next"><b>NEXT · </b>{r.next}</div></article>)}</div><div className="foot">この層の目的は「値段が上がったから資金流入」と短絡しないこと。実測フローが無い領域は明示的にPROXY/UNKNOWNのまま残し、一次・公式・許諾済みデータへ段階的に置き換える。</div></section>}
